name: ocr_albaran_app
description: "OCR para albaranes: detecta pedido y albarán, selección, corrección y envío por email."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_text_recognition: ^0.15.0
  image_picker: ^0.8.9
  image: ^4.0.15
  path_provider: ^2.0.15
  shared_preferences: ^2.0.18
  flutter_email_sender: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
